version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo installing dependencies...
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo start Pre-build and end it.
  
  build:
    commands:
      - echo Running unit tests...    
      - pytest test_app.py --junitxml=reports/results.xml --tb=short
      
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: .

reports:
  pytest_reports:
    files:
      - "reports/results.xml"
    discard-paths: yes
    file-format: JUNITXML